AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  okta-aws-sso-sicm

  Sample SAM Template for okta-aws-sso-sicm

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  OktaEventsApi:
    Type: "AWS::Serverless::Api"
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'https://britecore.okta.com'"
      Auth:
        DefaultAuthorizer: TokenAuth
        Authorizers:
          TokenAuth:
            FunctionArn: !GetAtt TokenAuthorizer.Arn
        ApiKeyRequired: true # sets for all methods
        UsagePlan:
          CreateUsagePlan: "PER_API"


  EventHookVerifier:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: verify.lambda_handler
      Runtime: python3.8
      Events:
        Verify:
          Type: Api
          Properties:
            RestApiId: !Ref OktaEventsApi
            Path: /
            Method: get

Outputs:
  OktaEventsApi:
    Description: "API Gateway endpoint URL for Prod stage for OktaEventsApi"
    Value: !Sub "https://${OktaEventsApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  EventHookVerifier:
    Description: "Perform initial endpoint verification with Okta"
    Value: !GetAtt EventHookVerifier.Arn
  EventHookVerifierIamRole:
    Description: "Implicit IAM Role created for EventHookVerifier function"
    Value: !GetAtt EventHookVerifierRole.Arn
